global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'node-exporter-prod'
    static_configs:
      - targets: ['node-exporter-prod:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: prod-agent

  - job_name: 'node-exporter-dev'
    static_configs:
      - targets: ['node-exporter-dev:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: dev-agent

